name: Pull Request
on:
  pull_request:
    branches:
      - master
      - 'feature/**'
      - 'bugfix/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Install and Build
      run: |
        npm ci
        npm run test:prod
        npm run lint
        npm run build:prod

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
